### ISSUE TITLE
Documentation for 3 instances of Kurento is wrong

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton.github.io#194]
When following this:
https://docs.bigbluebutton.org/2.2/customize.html#run-three-parallel-kurento-media-servers

Still only one instance is available.
Is this ONLY in 2.2.24 or up to later versions?

**Comment by ffdixon** [comment]
Fixed.

**Comment by lonesomewalker** [comment]
Unfortunately, when applying this like in the documentation, i still can't see 3 instances:

`
root@bbb ~ # netstat -tulpen | grep kur
tcp6       0      0 :::8888                 :::*                    LISTEN      113        470948      7207/kurento-media-
`

Either the documentation is wrong, or bbb-install.sh doesn't prepare the server for this :-/

**Comment by ffdixon** [comment]
Currently, `bbb-install.sh` doesn't setup a server with three Kurentos.  It could (and probably should).

**Comment by lonesomewalker** [comment]
So, when using bbb-install.sh this should generate a default installation, right?
No 3 servers.

Then applying the "enable", and bbb-conf --restart should spawn 3 instances?

Unfortunately, it doesn't.
Watching this on over 500 machines so far :-/

**Comment by lonesomewalker** [comment]
Okay, just a quick look in /etc/bigbluebutton/bbb-conf/apply-lib.sh says, the insertion of /etc/bigbluebutton/bbb-conf/apply-config.sh won't work this way, because it will be inserted in not_Called() which won't be called.

I didn't dive deeper, but as i understand in this quick look, there won't be a call to spawn 3 instances?

Please correct me :-)

**Comment by lonesomewalker** [comment]
Okay, now i know what is wrong :-)
The documentation should be much clearer about HOW to do this.
It is not a plain "write enableMultipleKurentos to apply-config.sh" ;-)
